name: Pipeline CI/CD con Pruebas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # token generado en SonarCloud
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=afuentesa-dev_mvc-demo \
            -Dsonar.organization=afuentesa-dev \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml      

      - name: Build Docker Image
        run: docker build -t mvc-demo .

      - name: Docker Compose
        run: docker compose up -d

      - name: Up
        run: |
          for i in {i..60}; do
            if curl -fsS http://localhost:8080/libros/inicio >/dev/null; then
              echo "Aplicación desplegada y lista."
              break
            fi
            echo "Esperando a que la aplicación se inicie... ($i/60)"
            sleep
          done

      - name: Firefox SetUp
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest'

      - name: Run Selenium UI Test
        env:
          BASE_URL: http://localhost:8080/libros/inicio
        run: mvn -B -Dtest=MvcDemoApplicationUITest test

      - name: Down
        if: always()
        run: docker compose down -v